In [5]:
import pandas
from pandas import DataFrame
import numpy

Giải nghĩa các cột dữ liệu:
* symbol : mã kí hiệu loại giao dịch
* base : mã đồng cơ sở
* quote : mã đồng báo giá
* Kline open/close time : thời gian mở/đóng của việc thu dữ liệu
* open price : Giá tại thời điểm đầu khi thu dữ liệu
* close price : giá tại thời điểm cuối cùng khi thu dữ liệu
* high price : giá cao nhất trong thời gian thu dữ liệu
* low price : giá thấp nhất trong thời gian thu dữ liệu
* volume : số lượng base đã được trao đổi
* quote asset volume : số lượng quote đã được trao đổi
* taker buy base volume : số lượng mua base (lệnh) (?)
* taker buy quote volume : số lượng mua quote (lệnh) (?)

In [35]:
symbols = pandas.read_csv('symbols.csv').drop(['Unnamed: 0'], axis=1)
data = pandas.read_csv('data.csv').drop(['Unnamed: 0'], axis=1)

In [39]:
data[data['base'].isin(['USDT','BUSD'])]

,Symbol,base,quote,Kline open time,Open price,High price,Low price,Close price,Volume,Kline Close time,Quote asset volume,Number of trades,Taker buy base asset volume,Taker buy quote asset volume,"Unused field, ignore"
197220,BUSDUSDT,BUSD,USDT,1669395600000,1.0006,1.0007,1.0006,1.0006,25115577.0,1669397399999,2.513104e+07,8352,3938314.0,3.941071e+06,0
197221,BUSDUSDT,BUSD,USDT,1669397400000,1.0006,1.0007,1.0006,1.0006,7449690.0,1669399199999,7.454586e+06,7717,4266354.0,4.269340e+06,0
197222,BUSDUSDT,BUSD,USDT,1669399200000,1.0006,1.0007,1.0005,1.0005,16078416.0,1669400999999,1.608827e+07,9494,2290278.0,2.291867e+06,0
197223,BUSDUSDT,BUSD,USDT,1669401000000,1.0006,1.0006,1.0005,1.0005,15665806.0,1669402799999,1.567464e+07,8324,10035726.0,1.004175e+07,0
197224,BUSDUSDT,BUSD,USDT,1669402800000,1.0005,1.0006,1.0005,1.0005,14914338.0,1669404599999,1.492302e+07,7465,12215374.0,1.222270e+07,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1229157,BUSDRON,BUSD,RON,1670943600000,4.6290,4.6300,4.6200,4.6210,5984.0,1670945399999,2.767234e+04,108,2086.0,9.651160e+03,0
1229158,BUSDRON,BUSD,RON,1670945400000,4.6200,4.6310,4.6200,4.6300,3618.0,1670947199999,1.673498e+04,42,1642.0,7.593482e+03,0
1229159,BUSDRON,BUSD,RON,1670947200000,4.6310,4.6310,4.6300,4.6310,3254.0,1670948999999,1.506902e+04,33,2998.0,1.388374e+04,0
1229160,BUSDRON,BUSD,RON,1670949000000,4.6300,4.6310,4.6300,4.6310,14415.0,1670950799999,6.674903e+04,92,7577.0,3.508909e+04,0
1229161,BUSDRON,BUSD,RON,1670950800000,4.6310,4.6310,4.6300,4.6310,3875.0,1670952599999,1.794304e+04,52,1795.0,8.312645e+03,0

In [36]:
symbols

         symbol   status baseAsset quoteAsset
0        ETHBTC  TRADING       ETH        BTC
1        LTCBTC  TRADING       LTC        BTC
2        BNBBTC  TRADING       BNB        BTC
3        NEOBTC  TRADING       NEO        BTC
4       QTUMETH  TRADING      QTUM        ETH
...         ...      ...       ...        ...
2132    HOOKBNB  TRADING      HOOK        BNB
2133   MAGICBTC  TRADING     MAGIC        BTC
2134  MAGICBUSD  TRADING     MAGIC       BUSD
2135  MAGICUSDT  TRADING     MAGIC       USDT
2136    BUSDRON  TRADING      BUSD        RON

[2137 rows x 4 columns]

In [38]:
# print("The following inverse pairs exist:")
# for index, row in symbols.iterrows():
#     for index2, row2 in symbols.iterrows():
#         if index != index2 and row['baseAsset'] == row2['quoteAsset'] and row['quoteAsset'] == row2['baseAsset']:
#             print(f"{row['symbol']} and {row2['symbol']}")
duplicate_symbols = []
def func(symbol_row):
    matches = symbols.apply(lambda row: symbol_row["baseAsset"] == row["quoteAsset"] and row["baseAsset"] == symbol_row["quoteAsset"], axis=1)
    if matches.any():
        duplicate_symbols.append(symbol_row["symbol"])
        return symbol_row
    return "Fail"

symbols.apply(lambda symbol_row: func(symbol_row), axis=1)

BTCTUSD has return matches
TUSDBTC has return matches
ETHTUSD has return matches
TUSDETH has return matches
TUSDBNB has return matches
PAXBTC has return matches
PAXBNB has return matches
PAXETH has return matches
USDCBNB has return matches
BNBPAX has return matches
BTCPAX has return matches
ETHPAX has return matches
BNBTUSD has return matches
BNBUSDC has return matches
BKRWUSDT has return matches
BKRWBUSD has return matches
DAIBNB has return matches
DAIBTC has return matches
DAIUSDT has return matches
DAIBUSD has return matches
USDTBKRW has return matches
BUSDBKRW has return matches
BTCDAI has return matches
BNBDAI has return matches
USDTDAI has return matches
BUSDDAI has return matches
USTBTC has return matches
BTCUST has return matches

0       Fail
1       Fail
2       Fail
3       Fail
4       Fail
        ...
2132    Fail
2133    Fail
2134    Fail
2135    Fail
2136    Fail
Length: 2137, dtype: object

In [5]:
uni = pandas.concat([symbols['baseAsset'],symbols['quoteAsset']]).unique() # co 525 loai coin
arr = numpy.concatenate([symbols['baseAsset'],symbols['quoteAsset']])
count = dict()

for i in uni:
    count[i] = numpy.count_nonzero(arr == i)
pandas.Series({k: v for k, v in sorted(count.items(), key=lambda item: item[1],reverse=True)}).head(10)
# 5 loại đồng tiền đầu tiên xuất hiện cực kì nhiều, có thể đây là 5 loại đồng tiền nền của sàn (xuất hiện ở khoảng trên 50% loại đồng, tới khoảng 90%)
# bằng một số tra cứu, BUSD thuộc về đông tiền ổn định, và USDT cố định ở mức 1$, nên ta có thể coi như 3 đồng này là đồng nền chính của sàn
# BTC, ETH, BNB tuy xuất hiện nhiều nhưng giá không ổn định trên thị trường khi quy về tiền thật, nên không thể làm mốc để so sánh được

BTC     437
USDT    429
BUSD    390
BNB     294
ETH     240
TRY      79
EUR      52
USDC     46
PAX      40
TUSD     37
dtype: int64

In [55]:
base_coin = ['BUSD','USDT']

In [77]:
f_symbols =  symbols[symbols.baseAsset.isin(base_coin) | symbols.quoteAsset.isin(base_coin)]
f_symbols = f_symbols[~(f_symbols.baseAsset.isin(base_coin) & f_symbols.quoteAsset.isin(base_coin))]
f_symbols

         symbol   status baseAsset quoteAsset
11      BTCUSDT  TRADING       BTC       USDT
12      ETHUSDT  TRADING       ETH       USDT
98      BNBUSDT  TRADING       BNB       USDT
125     BCCUSDT    BREAK       BCC       USDT
141     NEOUSDT  TRADING       NEO       USDT
...         ...      ...       ...        ...
2130   HOOKUSDT  TRADING      HOOK       USDT
2131   HOOKBUSD  TRADING      HOOK       BUSD
2134  MAGICBUSD  TRADING     MAGIC       BUSD
2135  MAGICUSDT  TRADING     MAGIC       USDT
2136    BUSDRON  TRADING      BUSD        RON

[817 rows x 4 columns]

In [64]:
f_data = data[data.Symbol.isin(f_symbols.symbol)]
f_data

,Symbol,base,quote,Kline open time,Open price,High price,Low price,Close price,Volume,Kline Close time,Quote asset volume,Number of trades,Taker buy base asset volume,Taker buy quote asset volume,"Unused field, ignore"
8650,BTCUSDT,BTC,USDT,1669395600000,16485.140,16512.430,16474.29,16483.270,3369.76766,1669397399999,5.557611e+07,81870,1723.18461,2.842171e+07,0
8651,BTCUSDT,BTC,USDT,1669397400000,16483.270,16536.350,16482.98,16510.380,3892.49531,1669399199999,6.427000e+07,91509,2058.71422,3.399223e+07,0
8652,BTCUSDT,BTC,USDT,1669399200000,16509.520,16528.600,16502.77,16509.400,2466.67932,1669400999999,4.073370e+07,61263,1246.75916,2.058911e+07,0
8653,BTCUSDT,BTC,USDT,1669401000000,16508.950,16518.590,16477.13,16495.430,2500.32611,1669402799999,4.126059e+07,59827,1169.95110,1.930727e+07,0
8654,BTCUSDT,BTC,USDT,1669402800000,16495.430,16553.880,16494.01,16515.200,2949.47675,1669404599999,4.872746e+07,66479,1564.85203,2.585432e+07,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1229157,BUSDRON,BUSD,RON,1670943600000,4.629,4.630,4.62,4.621,5984.00000,1670945399999,2.767234e+04,108,2086.00000,9.651160e+03,0
1229158,BUSDRON,BUSD,RON,1670945400000,4.620,4.631,4.62,4.630,3618.00000,1670947199999,1.673498e+04,42,1642.00000,7.593482e+03,0
1229159,BUSDRON,BUSD,RON,1670947200000,4.631,4.631,4.63,4.631,3254.00000,1670948999999,1.506902e+04,33,2998.00000,1.388374e+04,0
1229160,BUSDRON,BUSD,RON,1670949000000,4.630,4.631,4.63,4.631,14415.00000,1670950799999,6.674903e+04,92,7577.00000,3.508909e+04,0
1229161,BUSDRON,BUSD,RON,1670950800000,4.631,4.631,4.63,4.631,3875.00000,1670952599999,1.794304e+04,52,1795.00000,8.312645e+03,0

In [65]:
f_data[~f_data.quote.isin(base_coin)] # Các giá trị quy đổi cần điều chỉnh lại

,Symbol,base,quote,Kline open time,Open price,High price,Low price,Close price,Volume,Kline Close time,Quote asset volume,Number of trades,Taker buy base asset volume,Taker buy quote asset volume,"Unused field, ignore"
235280,BUSDRUB,BUSD,RUB,1669395600000,60.350,60.360,60.02,60.040,5645.0,1669397399999,339840.880,46,353.0,21287.580,0
235281,BUSDRUB,BUSD,RUB,1669397400000,60.060,60.140,60.01,60.030,1550.0,1669399199999,93056.620,10,230.0,13824.880,0
235282,BUSDRUB,BUSD,RUB,1669399200000,60.090,60.400,60.01,60.260,58045.0,1669400999999,3505179.650,37,57252.0,3457475.550,0
235283,BUSDRUB,BUSD,RUB,1669401000000,60.260,60.310,60.16,60.160,1105.0,1669402799999,66526.270,13,87.0,5243.550,0
235284,BUSDRUB,BUSD,RUB,1669402800000,60.200,60.240,60.15,60.150,2850.0,1669404599999,171521.070,30,1128.0,67913.480,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1229157,BUSDRON,BUSD,RON,1670943600000,4.629,4.630,4.62,4.621,5984.0,1670945399999,27672.337,108,2086.0,9651.160,0
1229158,BUSDRON,BUSD,RON,1670945400000,4.620,4.631,4.62,4.630,3618.0,1670947199999,16734.982,42,1642.0,7593.482,0
1229159,BUSDRON,BUSD,RON,1670947200000,4.631,4.631,4.63,4.631,3254.0,1670948999999,15069.018,33,2998.0,13883.738,0
1229160,BUSDRON,BUSD,RON,1670949000000,4.630,4.631,4.63,4.631,14415.0,1670950799999,66749.027,92,7577.0,35089.087,0
1229161,BUSDRON,BUSD,RON,1670950800000,4.631,4.631,4.63,4.631,3875.0,1670952599999,17943.045,52,1795.0,8312.645,0

In [76]:
# kiểm tra số đồng có trong bảng
print( 'So luong coin co trong data: ', pandas.concat([f_data.base,f_data.quote]).nunique()) # số lượng thấp hơn khi tính ở trên, đó là do một số đồng ko còn hiện hữu nữa
print( 'So luong coin con giao dich: ', pandas.concat([symbols[symbols.status == 'TRADING'].baseAsset ,symbols[symbols.status == 'TRADING'].quoteAsset]).nunique())

So luong coin co trong data:  372
So luong coin con giao dich:  378

Với kết quả trên thì công việc lọc ra bảng data cho ra giá trị thực của coin thực sự ổn