In [22]:
import pandas
from pandas import DataFrame
import numpy

### Giải nghĩa các cột dữ liệu:
* symbol : mã kí hiệu loại giao dịch
* base : mã đồng cơ sở
* quote : mã đồng báo giá
* Kline open/close time : thời gian mở/đóng của việc thu dữ liệu
* open price : Giá tại thời điểm đầu khi thu dữ liệu
* close price : giá tại thời điểm cuối cùng khi thu dữ liệu
* high price : giá cao nhất trong thời gian thu dữ liệu
* low price : giá thấp nhất trong thời gian thu dữ liệu
* volume : số lượng base đã được trao đổi
* quote asset volume : số lượng quote đã được trao đổi
* taker buy base volume : số lượng mua base (lệnh) (?)
* taker buy quote volume : số lượng mua quote (lệnh) (?)

In [23]:
symbols = pandas.read_csv('Data\symbols.csv').drop(['Unnamed: 0'], axis=1)
data = pandas.read_csv('Data\data.csv').drop(['Unnamed: 0'], axis=1)

In [24]:
data.head()

,Symbol,base,quote,Kline open time,Open price,High price,Low price,Close price,Volume,Kline Close time,Quote asset volume,Number of trades,Taker buy base asset volume,Taker buy quote asset volume,"Unused field, ignore"
0,ETHBTC,ETH,BTC,1669395600000,0.072026,0.072222,0.072026,0.072222,1342.1624,1669397399999,96.776126,2657,794.6663,57.298344,0
1,ETHBTC,ETH,BTC,1669397400000,0.072222,0.072335,0.072117,0.072162,1185.9640,1669399199999,85.640393,2727,560.9044,40.508977,0
2,ETHBTC,ETH,BTC,1669399200000,0.072163,0.072263,0.072101,0.072189,813.4793,1669400999999,58.717779,1862,359.8931,25.975732,0
3,ETHBTC,ETH,BTC,1669401000000,0.072188,0.072261,0.072161,0.072212,936.2168,1669402799999,67.599402,1816,470.6928,33.988586,0
4,ETHBTC,ETH,BTC,1669402800000,0.072223,0.072479,0.072197,0.072375,1115.5725,1669404599999,80.727099,3088,593.4310,42.945939,0

### Kiểm tra trùng lặp symbols

In [54]:
symbols[symbols.symbol.isin(symbols.quoteAsset+symbols.baseAsset)] #cac symbols co trung lap

        symbol   status baseAsset quoteAsset
312    BTCTUSD    BREAK       BTC       TUSD
313    TUSDBTC    BREAK      TUSD        BTC
314    ETHTUSD    BREAK       ETH       TUSD
315    TUSDETH    BREAK      TUSD        ETH
316    TUSDBNB    BREAK      TUSD        BNB
390     PAXBTC    BREAK       PAX        BTC
391     PAXBNB    BREAK       PAX        BNB
393     PAXETH    BREAK       PAX        ETH
397    USDCBNB    BREAK      USDC        BNB
404     BNBPAX    BREAK       BNB        PAX
405     BTCPAX    BREAK       BTC        PAX
406     ETHPAX    BREAK       ETH        PAX
412    BNBTUSD    BREAK       BNB       TUSD
416    BNBUSDC    BREAK       BNB       USDC
839   BKRWUSDT    BREAK      BKRW       USDT
840   BKRWBUSD    BREAK      BKRW       BUSD
871     DAIBNB    BREAK       DAI        BNB
872     DAIBTC    BREAK       DAI        BTC
873    DAIUSDT    BREAK       DAI       USDT
874    DAIBUSD    BREAK       DAI       BUSD
899   USDTBKRW    BREAK      USDT       BKRW
900   BUSDBKRW    BREAK      BUSD       BKRW
919     BTCDAI  TRADING       BTC        DAI
921     BNBDAI  TRADING       BNB        DAI
922    USDTDAI  TRADING      USDT        DAI
923    BUSDDAI  TRADING      BUSD        DAI
1851    USTBTC    BREAK       UST        BTC
2005    BTCUST    BREAK       BTC        UST

In [75]:
check = symbols[symbols.symbol.isin(symbols.quoteAsset+symbols.baseAsset)]
check = check[check.status == 'TRADING']
data[data.Symbol.isin(check.symbol)].head()

,Symbol,base,quote,Kline open time,Open price,High price,Low price,Close price,Volume,Kline Close time,Quote asset volume,Number of trades,Taker buy base asset volume,Taker buy quote asset volume,"Unused field, ignore"
376275,BTCDAI,BTC,DAI,1669395600000,16477.22,16501.20,16465.97,16480.76,0.31156,1669397399999,5137.050515,17,0.24136,3980.717036,0
376276,BTCDAI,BTC,DAI,1669397400000,16490.68,16522.10,16490.68,16495.18,0.32764,1669399199999,5406.276577,15,0.07485,1234.698275,0
376277,BTCDAI,BTC,DAI,1669399200000,16500.00,16507.18,16490.98,16492.27,2.78289,1669400999999,45904.759939,113,2.56464,42304.614270,0
376278,BTCDAI,BTC,DAI,1669401000000,16494.60,16507.99,16469.46,16483.78,1.08304,1669402799999,17864.162541,31,1.04011,17156.594413,0
376279,BTCDAI,BTC,DAI,1669402800000,16491.37,16529.81,16491.37,16521.93,0.07737,1669404599999,1278.299528,3,0.05006,827.482289,0

In [76]:
data[data.Symbol.isin(check.quoteAsset+check.baseAsset)].head()

Empty DataFrame
Columns: [Symbol, base, quote, Kline open time, Open price, High price, Low price, Close price, Volume, Kline Close time, Quote asset volume, Number of trades, Taker buy base asset volume, Taker buy quote asset volume, Unused field, ignore]
Index: []

Vẫn tồn tại một số đồng trùng lắp, với đa số đã bị BREAK(không còn hiện hữu), còn các đồng có gắn TRADING thì cũng hiện không còn data, nên có thể coi là không có trùng lắp ở đây

### Kiểm tra giá trị của các token 

làm theo các bước:
- kiếm ra các đồng tiền xuất hiện nhiều nhất ở các giao dịch
- tra cứu thông tin về các đồng tiền đó
- lọc lại dữ liệu theo quy đổi về đồng tiền nền (coi như đồng này không biến động)

In [25]:
uni = pandas.concat([symbols['baseAsset'],symbols['quoteAsset']]).unique() # co 525 loai coin
arr = numpy.concatenate([symbols['baseAsset'],symbols['quoteAsset']])
count = dict()

for i in uni:
    count[i] = numpy.count_nonzero(arr == i)
pandas.Series({k: v for k, v in sorted(count.items(), key=lambda item: item[1],reverse=True)}).head(10)

BTC     437
USDT    429
BUSD    390
BNB     294
ETH     240
TRY      79
EUR      52
USDC     46
PAX      40
TUSD     37
dtype: int64

- 5 loại đồng tiền đầu tiên xuất hiện cực kì nhiều, có thể đây là 5 loại đồng tiền nền của sàn (xuất hiện ở khoảng trên 50% loại đồng, tới khoảng 90%)
- bằng một số tra cứu, BUSD và USDT thuộc về đông tiền ổn định ở mức 1$, nên ta có thể coi như 2 đồng này là đồng nền chính của sàn
- BTC, ETH, BNB tuy xuất hiện nhiều nhưng giá không ổn định trên thị trường, nên không thể làm mốc để so sánh được

In [26]:
base_coin = ['BUSD','USDT'] # đồng tiền ổn định giá

In [27]:
f_symbols =  symbols[symbols.baseAsset.isin(base_coin) | symbols.quoteAsset.isin(base_coin)]
f_symbols = f_symbols[~(f_symbols.baseAsset.isin(base_coin) & f_symbols.quoteAsset.isin(base_coin))]
f_symbols.head()

      symbol   status baseAsset quoteAsset
11   BTCUSDT  TRADING       BTC       USDT
12   ETHUSDT  TRADING       ETH       USDT
98   BNBUSDT  TRADING       BNB       USDT
125  BCCUSDT    BREAK       BCC       USDT
141  NEOUSDT  TRADING       NEO       USDT

In [28]:
f_data = data[data.Symbol.isin(f_symbols.symbol)]
f_data.head()

,Symbol,base,quote,Kline open time,Open price,High price,Low price,Close price,Volume,Kline Close time,Quote asset volume,Number of trades,Taker buy base asset volume,Taker buy quote asset volume,"Unused field, ignore"
8650,BTCUSDT,BTC,USDT,1669395600000,16485.14,16512.43,16474.29,16483.27,3369.76766,1669397399999,5.557611e+07,81870,1723.18461,2.842171e+07,0
8651,BTCUSDT,BTC,USDT,1669397400000,16483.27,16536.35,16482.98,16510.38,3892.49531,1669399199999,6.427000e+07,91509,2058.71422,3.399223e+07,0
8652,BTCUSDT,BTC,USDT,1669399200000,16509.52,16528.60,16502.77,16509.40,2466.67932,1669400999999,4.073370e+07,61263,1246.75916,2.058911e+07,0
8653,BTCUSDT,BTC,USDT,1669401000000,16508.95,16518.59,16477.13,16495.43,2500.32611,1669402799999,4.126059e+07,59827,1169.95110,1.930727e+07,0
8654,BTCUSDT,BTC,USDT,1669402800000,16495.43,16553.88,16494.01,16515.20,2949.47675,1669404599999,4.872746e+07,66479,1564.85203,2.585432e+07,0

In [29]:
f_data[~f_data.quote.isin(base_coin)].head() # Các giá trị quy đổi cần điều chỉnh lại

,Symbol,base,quote,Kline open time,Open price,High price,Low price,Close price,Volume,Kline Close time,Quote asset volume,Number of trades,Taker buy base asset volume,Taker buy quote asset volume,"Unused field, ignore"
235280,BUSDRUB,BUSD,RUB,1669395600000,60.35,60.36,60.02,60.04,5645.0,1669397399999,339840.88,46,353.0,21287.58,0
235281,BUSDRUB,BUSD,RUB,1669397400000,60.06,60.14,60.01,60.03,1550.0,1669399199999,93056.62,10,230.0,13824.88,0
235282,BUSDRUB,BUSD,RUB,1669399200000,60.09,60.40,60.01,60.26,58045.0,1669400999999,3505179.65,37,57252.0,3457475.55,0
235283,BUSDRUB,BUSD,RUB,1669401000000,60.26,60.31,60.16,60.16,1105.0,1669402799999,66526.27,13,87.0,5243.55,0
235284,BUSDRUB,BUSD,RUB,1669402800000,60.20,60.24,60.15,60.15,2850.0,1669404599999,171521.07,30,1128.0,67913.48,0

In [30]:
# kiểm tra số đồng có trong bảng
print( 'number of token in data: ', pandas.concat([f_data.base,f_data.quote]).nunique()) # số lượng thấp hơn khi tính ở trên, đó là do một số đồng ko còn hiện hữu nữa
print( 'number of token still trading: ', pandas.concat([symbols[symbols.status == 'TRADING'].baseAsset ,symbols[symbols.status == 'TRADING'].quoteAsset]).nunique())

number of token in data:  372
number of token still trading:  378

biến bảng trên thành giá trị quy đổi qua đồng tiền nền (Thực tế đã là bảng hiện tại) <br>
tạo 1 bảng giá tiền của đồng tiền theo symbols <br>
Cần đổi lại các đồng tiền có quote không nằm trong 'base_coin' theo quy tắc:
- base <-> quote
- Volume <-> Quote asset volume
- Taker buy base asset volume <-> Taker buy quote asset volume
- Các giá trị tiền tệ: New = 1 / Old

In [31]:
#only run this cell one
temp = f_data[~f_data.quote.isin(base_coin)]
f_data[~f_data.quote.isin(base_coin)] = pandas.concat([
    temp[['Symbol','quote','base' ,'Kline open time']],
    1/temp[['Open price','High price','Low price','Close price']],
    temp[['Quote asset volume','Kline Close time','Volume','Number of trades','Taker buy quote asset volume','Taker buy base asset volume','Unused field, ignore']]
],axis=1)

# f_data now is the data of "true value" of the token
all(f_data.quote.isin(base_coin))

C:\Users\TNT\AppData\Local\Temp\ipykernel_13772\1115278007.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  f_data[~f_data.quote.isin(base_coin)] = pandas.concat([

In [40]:
f_data.to_csv("Data/token_price.csv",index=False)

Với kết quả trên thì công việc lọc ra bảng data cho ra giá trị thực của coin thực sự ổn
___